// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpymrggymkhuodlqnruo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhweW1yZ2d5bWtodW9kbHFucnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzI5NDQsImV4cCI6MjA2MDUwODk0NH0.S_Rqc7gO3woilu02792B3CMyz22jRSzR_qGavHhjp9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);